version: "3.9"

services:
  adminapp:
    build:
      context: ./AdminApp
      dockerfile: Dockerfile
    image: adminapp:prod
    container_name: adminapp
    restart: unless-stopped
    ports:
      - "7000:80"

  clientapp:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    image: clientapp:prod
    container_name: clientapp
    restart: unless-stopped
    ports:
      - "7001:80"

